RECTANGLE_CHARACTER = 'RECTANGLE_CHARACTER'
LINE_CHARACTER = 'LINE_CHARACTER'

LOWER_CANVAS_COMMAND = 'c'
LOWER_LINE_COMMAND = 'l'
LOWER_RECTANGLE_COMMAND = 'r'
LOWER_BUCKETFILL_COMMAND = 'b'
LOWER_AVAILABLE_COMMANDS = [
    LOWER_CANVAS_COMMAND,
    LOWER_LINE_COMMAND,
    LOWER_RECTANGLE_COMMAND,
    LOWER_BUCKETFILL_COMMAND
]
